name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install
      run: yarn install
      env:
        CI: true
    - name: Build and Test
      run: make test
      env:
        CI: true
